### ISSUE TITLE
Version of Python? 

### ISSUE THREAD

**Issue by erickmiller** [akapur/pyiqfeed#1]
This looks like a really useful project.  Hoping to get it running.  

I'm getting several syntax errors that I think are related to the version of Python (I'm running 2.7 on Linux) due to some library dependencies.  Is this code written and tested for python 3x or python 2x?

Error:
   from pyiqfeed.service import FeedService
  File "./pyiqfeed/service.py", line 8
    product: str,
           ^
SyntaxError: invalid syntax

Just signed up for my iqfeed account so hopefully I can get this working before they start charging me for it!  I've already installed wine and the client applications and seem to be able to successfully connect that way.  Thanks

**Comment by erickmiller** [comment]
Ok, from general syntax I figured out this is definitely Python 3x code.  Also figured out through the use of your import of the 'typing' library that it is Python 3.5 since this import statement does not work with earlier versions, ie Python 3.4 etc.   So, I installed Python 3.5 and dependencies and re-tested, code appears to work.   Yay!   May I suggest you put something about the Python version in the Readme?  Otherwise this project looks pretty cool and appears to be connecting nicely to iqfeed and getting all the datas (with 3.5 anyways).   Thanks!

**Comment by erickmiller** [comment]
Upon some further testing I am noticing an error that I thought you should know about.  It appears a large amount of data retrieval is still working but this error is thrown at the very beginning.  Not sure what's causing it yet or how to fix it, will take a closer look at it tomorrow.  Any ideas?   Thanks

QuoteListener: Authorization Key Received: ######
QuoteListener: Feed Connected
QuoteListener: IP Addresses Used: ##.###.###.## #####
QuoteListener: Customer Information:
{'port': #####,  'flags': 'QT_API', 'token': '#######', 'rt_exchs': ['', 'BLOOMBERG', 'TRIAL', 'RT_TRADER', 'COMTEX', 'PRIMEZONE', 'INTERNET_WIRE', 'DTNNEWS', 'SCROLLNEWS', 'EXFUND', 'BENZINGA', ''], 'version': '5.2.3.0', 'ip_add': ##.###.###.###', 'max_sym': 500, 'svc_t': False}
Exception in thread RunningInIDE-reader:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(_self._args, *_self._kwargs)
  File "pyiqfeed/conn.py", line 322, in __call__
    self.process_messages()
  File "pyiqfeed/conn.py", line 366, in process_messages
    handle_func(fields)
  File "pyiqfeed/conn.py", line 384, in process_system_message
    processing_func(fields)
  **File "pyiqfeed/conn.py", line 901, in process_fundamental_fieldnames
    "%s not found in QuoteConn.dtn_fundamental_fields" % field)
RuntimeError: Option Premium Multiplier not found in QuoteConn.dtn_fundamental_fields**

**Comment by akapur** [comment]
Python 3.5

**Comment by akapur** [comment]
What are you running? Send me a copy of your code please.

**Comment by erickmiller** [comment]
Cool, thanks. Yeah, I should have mentioned -- the error came from running the code from your test example script:

https://github.com/akapur/pyiqfeed/blob/master/example.py

Also am running the latest version of the DTN iqfeed datafeed binary v 5.2.4.0 from: http://www.iqfeed.net/index.cfm?displayaction=support&section=download 
Running on Ubuntu  via wine if that helps.  

Also tried searching the IQ feed forums here: 
http://forums.iqfeed.net/index.cfm?page=home&categoryID=4
But found nothing related to: Option Premium Multiplier 

I noticed in conn.py there is a list data structure fundamental_fields of the class QuoteConn which doesn't contain Option Premium Multiplier so maybe my data subscription is returning different data types than what are contained in fundamental_fields ?   I'm running the trial version of IQ feed which will give me a bunch of feeds for free that are normally upgrades and cost extra.   Maybe there is a difference in the data feeds I'm getting back -- here are the feeds I'm currently getting (printed from your cool diagnostic message) maybe these differ from the ones you coded and tested with?

 'BLOOMBERG', 'TRIAL', 'RT_TRADER', 'COMTEX', 'PRIMEZONE', 'INTERNET_WIRE', 'DTNNEWS', 'SCROLLNEWS', 'EXFUND', 'BENZINGA'

**Comment by akapur** [comment]
Haven't updated to latest version yet. In Europe on a road trip until Aug 9. Will look at it on my return.

**Comment by erickmiller** [comment]
Cool, have fun in Europe and thanks.  I'll let you know if I find out more in the mean time.  If I happen to fix whatever's going on, I'll submit a pull request.  Very cool library, super useful.   

One quick question I have -=- and I'm also new to the IQ feed API so apologies if this is an obvious question -- but in terms of getting data from the news feeds -- I noticed how to set NEWSON and NEWSOFF in conn.py but does the library have any methods exposed for receiving and handling the news stream?  

If so, when you have a chance could you post a small snippet of code that shows this functionality? 

Thanks again!

**Comment by erickmiller** [comment]
Hey Ashwin,

So I got pretty busy the last couple weeks but finally got back to this, then found, and fixed the error.  It was due to DTN adding some new fields in the Level 1 Fundamental Data that weren't in the QuoteConn class.  Scroll to the bottom of this page to see the description of the fields (requires iqfeed developer login) http://www.iqfeed.net/dev/api/docs/Level1FundamentalMessage.cfm 

I forked your repo, made these quick fixes and created a pull request to merge -- you can see here: https://github.com/akapur/pyiqfeed/pull/2

Next I need to figure out how to get RealTime news headlines as well as full Level 1 Equity Option Chains  (Symbol, Strike, Last, Change, Bid, Ask, Volume, and Open Interest).  Currently the equity option chains returned in the example code is only OPRA OSI which is SYMBOL, Expiration Year Day Month, and Strike Price -- but I'm looking for the Bid, Ask, Volume and Open Interest.   

Any tips on using this API to get a full level 1 option chain as well as real time news headlines?  

Thanks in advance,
Erick

**Comment by akapur** [comment]
Merged. Thanks for the fix.

**Comment by stephenrs** [comment]
Hi @akapur I'm having a similar error to what was originally posted here, except in my case, it appears that pyiqfeed is expecting a fundamental field that IQfeed is not sending. Here's the output from running 

`python3 example.py -t`

Trades Listener: Authorization Key Received: #####
Trades Listener: Feed Disconnected
Trades Listener: IP Addresses Used: ##.##.##.## #####
Trades Listener: Customer Information:
CustomerInfoMsg(svc_type=True, ip_address='##.##.##.##', port=#####, token='######', version='5.2.5.0', rt_exchanges=['', 'NYSE', 'NASDAQ', 'DL-NYMEX', 'DL-COMEX', 'FOREX_PREMIUM', 'RT_TRADER', 'COMTEX', 'PRIMEZONE', 'INTERNET_WIRE', 'DTNNEWS', 'SCROLLNEWS', 'EXFUND', 'BENZINGA', ''], max_symbols=500, flags='QT_API')
Exception in thread pyiqfeed-Example-trades-only-reader:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/srv/www/feed1.wavebasis.com/marketfeed/pyiqfeed/pyiqfeed/conn.py", line 207, in __call__
    self._process_messages()
  File "/srv/www/feed1.wavebasis.com/marketfeed/pyiqfeed/pyiqfeed/conn.py", line 254, in _process_messages
    handle_func(fields)
  File "/srv/www/feed1.wavebasis.com/marketfeed/pyiqfeed/pyiqfeed/conn.py", line 286, in _process_system_message
    processing_func(fields)
  File "/srv/www/feed1.wavebasis.com/marketfeed/pyiqfeed/pyiqfeed/conn.py", line 982, in _process_fundamental_fieldnames
    raise UnexpectedField(err_msg)
**pyiqfeed.exceptions.UnexpectedField: Option Premium Multiplier not found in FUNDAMENTAL FIELDNAMES in pyiqfeed-Example-trades-only**

Do you have any advice on how to get around this?

Thanks so much for all your hard work!

**Comment by akapur** [comment]
What version of IQFeed are you running?

**Comment by stephenrs** [comment]
5.2.5.0

**Comment by akapur** [comment]
I just ran exactly what you ran in Anaconda Python 3.6 5 times with no problems. Did you make any changes at all to example.py or any other file?

**Comment by stephenrs** [comment]
I noticed that IQFeed has released 5.2.6.0, so I upgraded/installed clean, and now the command I was having problems with is running fine. I have needed to experiment with other client versions in the past, so there's a chance that my client was just out of date before the upgrade.

Thanks for checking into this, and sorry if I wasted your time.
