### ISSUE TITLE
Missing field in streaming news named tuple

### ISSUE THREAD

**Issue by ivan-vasilev** [akapur/pyiqfeed#15]
[On line 702 of conn.py](https://github.com/akapur/pyiqfeed/blob/master/pyiqfeed/conn.py#L703) the line should become:
        "story_id", "distributor", "symbol_list", "story_date", "story_time", "headline"))
e.g. a field called _story_date_ is missing, causing exception in runtime, when the namedtuple is instantiated [here.](https://github.com/akapur/pyiqfeed/blob/master/pyiqfeed/conn.py#L785)

**Comment by akapur** [comment]
Fixed. Thanks for noticing this. I don't exercise this particular code in the stuff I run.

**Comment by akapur** [comment]
Fixed
