### ISSUE TITLE
How do you get Product ID?

### ISSUE THREAD

**Issue by psx369** [akapur/pyiqfeed#18]
How do you get the product ID from DTN?

**Comment by akapur** [comment]
Subscribe for a developer license. It's about 300 bucks a year plus regular iqfeed charges.

**Comment by psx369** [comment]
I've purchased a subscription. However, how do I get the ID of the subscription so I can put this in the config file?

**Comment by akapur** [comment]
Ask DTN. I don’t do support for them.
