### ISSUE TITLE
How to run code for the first time. Getting exception

### ISSUE THREAD

**Issue by karunkrishna** [akapur/pyiqfeed#20]
Lauches the IQFeed client and logs in successfully. But when I try to run the example.py code and request  "Run Level 1 Quote"

C:\Users\A\PycharmProjects\iqfeed>python example.py -l
Starting python code
Inside launch service
Level 1 Listener: Authorization Key Received: 99999
Level 1 Listener: Feed Connected
Level 1 Listener: IP Addresses Used: 66.112.156.181 60004
Level 1 Listener: Customer Information:
CustomerInfoMsg(svc_type=True, ip_address='66.112.156.225', port=60007, token='ABCD', version='5.2.5.0', rt_exchanges=['', 'RT_TRADER', 'COMTEX', 'PRIMEZONE', 'INTERNE
T_WIRE', 'DTNNEWS', 'SCROLLNEWS', 'EXFUND', 'BENZINGA', ''], max_symbols=500, flags='QT_API')
Exception in thread pyiqfeed-Example-lvl1-reader:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\A\PycharmProjects\iqfeed\pyiqfeed\conn.py", line 207, in __call__
    self._process_messages()
  File "C:\Users\A\PycharmProjects\iqfeed\pyiqfeed\conn.py", line 254, in _process_messages
    handle_func(fields)
  File "C:\Users\A\PycharmProjects\iqfeed\pyiqfeed\conn.py", line 286, in _process_system_message
    processing_func(fields)
  File "C:\Users\A\PycharmProjects\iqfeed\pyiqfeed\conn.py", line 982, in _process_fundamental_fieldnames
    raise UnexpectedField(err_msg)
pyiqfeed.exceptions.UnexpectedField: Option Premium Multiplier not found in FUNDAMENTAL FIELDNAMES in pyiqfeed-Example-lvl1

**Comment by akapur** [comment]
What version of iqfeed are you running? Have you made any changes to the code?

**Comment by karunkrishna** [comment]
![image](https://user-images.githubusercontent.com/2157606/27509677-5284c4b6-58d0-11e7-81ca-51216aaaa2c5.png)

Let me try upgrading, see if that addresses the issue. I'm assuming that I need 5.2.50+ to run?

**Comment by karunkrishna** [comment]
That did the trick. 
```
 (datetime.date(2017, 6, 23), datetime.timedelta(0, 72060), 243.13, 243.13, 243.13, 243.13, 66986801, 0, 0)
 (datetime.date(2017, 6, 23), datetime.timedelta(0, 72000), 243.18, 243.19, 243.18, 243.19, 66986801, 2300, 0)
 (datetime.date(2017, 6, 23), datetime.timedelta(0, 71880), 243.18, 243.18, 243.18, 243.18, 66984501, 500, 0)
 (datetime.date(2017, 6, 23), datetime.timedelta(0, 71820), 243.18, 243.18, 243.18, 243.18, 66984001, 2017, 0)
 (datetime.date(2017, 6, 23), datetime.timedelta(0, 71760), 243.17, 243.17, 243.17, 243.17, 66981901, 900, 0)
 (datetime.date(2017, 6, 23), datetime.timedelta(0, 71700), 243.15, 243.15, 243.15, 243.15, 66981001, 200, 0)
 (datetime.date(2017, 6, 23), datetime.timedelta(0, 71340), 243.17, 243.17, 243.17, 243.17, 66980801, 400, 0)
 (datetime.date(2017, 6, 23), datetime.timedelta(0, 71220), 243.18, 243.18, 243.18, 243.18, 66980401, 500, 0)
 (datetime.date(2017, 6, 23), datetime.timedelta(0, 71160), 243.17, 243.17, 243.17, 243.17, 66979901, 1500, 0)
 (datetime.date(2017, 6, 23), datetime.timedelta(0, 70860), 243.17, 243.17, 243.17, 243.17, 66978401, 100, 0)
 (datetime.date(2017, 6, 23), datetime.timedelta(0, 70800), 243.19, 243.2, 243.19, 243.2, 66978301, 1200, 0)
 (datetime.date(2017, 6, 23), datetime.timedelta(0, 70740), 243.2, 243.2, 243.19, 243.19, 66977101, 4000, 0)
```
