### ISSUE TITLE
Possible values for dtn_product_id = "PRODUCT_ID_FROM_DTN"

### ISSUE THREAD

**Issue by Sdoof** [akapur/pyiqfeed#26]
Hello

Thanks for putting this package together, I am really looking forward to test it and I am putting the required file together. 
While I can get both the login and password,  even the DTNIQ team is not sure about what is required for the first line(see below). Can you provide an example of plausible string this filed should take?
is it simply  dtn_product_id ="DTN.IQ"

` dtn_product_id = "PRODUCT_ID_FROM_DTN"
 dtn_login="Your_IQFEED_LOGIN"
 dtn_password="Your_IQFEED_PASSWORD"`

**Comment by akapur** [comment]
If you have a developer license from DTN, which also gives you access to documentation etc, you get a product ID. This is the Product ID to use here. The login and password are your regular login and password.

**Comment by yvessoete** [comment]
You can also fill in whatever you want, it works with anything

**Comment by andreireiand** [comment]
yvessoete - it doesn't seem to work with anything put in the product-id ... using 5.2.7.0, without a proper product-ID, I get:

Sorry, your Product and/or Service for the attempted login are incorrect. If you have recently changed products you may also need to change your type of service. Please contact DTN customer support for assistance. (1)

What version do you use?

**Comment by akapur** [comment]
Like I mentioned in the reply to your previous email, you need a developer license for IQFeed and when you get one, they will send you a product id. It’s like an api key. This is clearly documented in the repository.

yvessoete may have thought you were asking about a connection name.

**Comment by yssoe** [comment]
Are you sure you have a developer login and not a normal login? It looks to me this is the case.
