### ISSUE TITLE
Getting historical trade data for current day.

### ISSUE THREAD

**Issue by bryaan** [akapur/pyiqfeed#29]
I am calling the historical trade data request method with the current day as the start and end date.  But iqfeed says it has no data.  It works fine for previous days.  Is there some trick here?

```
   with iq.ConnConnector([history_conn]) as connector:
      data = history_conn.request_ticks_in_period(ticker, startDate, endDate, ascend=True, timeout=60)
     
```

**Comment by akapur** [comment]
I would ask DTN about that since it works for prior days.
