### ISSUE TITLE
Equity Option Chains only return OPRA OSI codes (and) Getting the News?

### ISSUE THREAD

**Issue by erickmiller** [akapur/pyiqfeed#3]
Glad the fixes worked out.  

Could you kindly give any quick tips on using the library to:

1) Get full Equity Option Chains (Symbol, Strike, Last, Change, Bid, Ask, Volume, and Open Interest)? 
Currently the example for equity option chains only returns OPRA OSI codes... 

2) Get real-time news feed? 

If this functionality isn't currently supported by the API please let me know - and if you can give me any quick pointers on where best to implement these features I will probably code this up and send another pull request because I need these features for what I'm working on.

Thanks in advance

**Comment by akapur** [comment]
1)      For equity option chains the way the IQFeed API works and the pyiqfeed package works is that when you request the chain you get symbols and then you have to get the data for those symbols yourself. So you can request a snapshot or request live market data for each of those symbols.

2)      I haven’t implemented news. I would subclass the FeedConn class to create a new NewsConn class to get it. Look at the implementations of any of the other ???Conn Classes.

**Comment by erickmiller** [comment]
Cool thanks for the pointers.  I finally had some block of time the last few days so I implemented this stuff and more!   Have been testing the code all day.  Just sent you pull request:

https://github.com/akapur/pyiqfeed/pull/5
