### ISSUE TITLE
Syntax Error while requesting live bar data

### ISSUE THREAD

**Issue by nwillemse** [akapur/pyiqfeed#36]
Hi, i'm running the example to retrieve live bar data, but I am getting a SYNTAX ERROR message back.  I don't have access to the api docs to see what changed with the api, but here is what I am running:

```
(global) eadu:pyiqfeed nwillemse$ python example.py -i
Bar Listener: Process Error:
['E', '!SYNTAX_ERROR!', '']
Bar Listener: Process Error:
['E', '!SYNTAX_ERROR!', '']
```

**Comment by akapur** [comment]
What version of IQFeed are you running? If you are running an old version of IQFeed, pyiqfeed may not work or an older release of pyiqfeed may work.
