### ISSUE TITLE
ModuleNotFoundError: No module named 'localconfig.passwords'

### ISSUE THREAD

**Issue by km-dawson** [akapur/pyiqfeed#37]
Error occurring when attemtping to run example.py (as shown in README). 

I have created the file passwords.py and stored it in the same folder as examples.py

(base) C:\Python_Dev\pyiqfeed-master>python ./example.py                                                                Traceback (most recent call last):                                                                                        File "./example.py", line 16, in <module>                                                                                 from localconfig.passwords import dtn_product_id, dtn_login, dtn_password                                           ModuleNotFoundError: No module named 'localconfig.passwords'

**Comment by akapur** [comment]
Change the line ending in localconfig.passwords to passwords or put he file passwords.py in a directory called localconfig which also contains a file called __init__.py

**Comment by km-dawson** [comment]
Works perfectly now, thanks!
