### ISSUE TITLE
I am seeing a delay of 10 mins (consistently) for livebar

### ISSUE THREAD

**Issue by karunkrishna** [akapur/pyiqfeed#38]
Have you experienced this problem?
Are you able to add a logger with current timestamp..and the resulting processed live bar to verify the time difference? I'm seeing consistent 10 minute delay. 

I noticed this when my limit orders were not getting filled against Interactive Brokers because the the pyiqfeed livebar has not "caught" up to realtime data. (I'm using pyiqfeed as the market data source for my strategy)

If you can confirm the above, it would give me some confidence to weed through my code to see if there is any bottleneck. Have you experienced this issue in the past? 

I am running your example code with parameter -i 
I have changed all the VerboseIQFeedListenter "print" statements to "logging" statements so that the timestamp differences were apparent 

![image](https://user-images.githubusercontent.com/2157606/51037698-e98e7200-157e-11e9-9d6b-7fb6dc4daa0a.png)

**Comment by akapur** [comment]
Are you enabled for real time data on IQFeed. You have to turn on non-delayed data and pay an additional fee for that.

**Comment by karunkrishna** [comment]
I am paying for the API and the IQFeed data for Stocks and Futures. Is there another subscription?

![image](https://user-images.githubusercontent.com/2157606/51042446-51968580-158a-11e9-8bb2-95c748776c66.png)

**Comment by akapur** [comment]
Are you paying exchange fees for real-time data for whatever exchange you are trading. If you are not you get delayed data.

**Comment by karunkrishna** [comment]
Damn! you are so right....I connected to Ninjatrader and it looks like that too is delayed by 10 minutes
Also, thank you for making this package!!!

If you can point me in the right direction:
1. Do you know who I need to make the real-time data request to? 
2. Is it a service IQFeed provides? 
3. How much is it monthly? 
4. Have you come across any python api for sourcing realtime data from interactive brokers?

![image](https://user-images.githubusercontent.com/2157606/51044986-7988e780-1590-11e9-8dcb-c2e42ce5dd1d.png)

**Comment by akapur** [comment]
Please call IQFeed customer support.

Thanks.
