### ISSUE TITLE
Intermittent exception raised during call to request_bars_in_period()

### ISSUE THREAD

**Issue by stephenrs** [akapur/pyiqfeed#41]
Hi,

I get the error/exception below occasionally, and I'm wondering if you can provide some insight, like:

- What condition does it signify?
- What is the best way to handle it?
- Is there something I can/should do to prevent it from happening in the first place?

```
Exception in thread iqfeed_history-reader:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "<my private path>/pyiqfeed/conn.py", line 201, in __call__
    self._process_messages()
  File "<my private path>/pyiqfeed/conn.py", line 248, in _process_messages
    handle_func(fields)
  File "<my private path>/pyiqfeed/conn.py", line 1735, in _process_datum
    self._req_buf[req_id].append(fields)
KeyError: 'H_0000000155'
```

This appears to be reproducible by requesting the ticker "USDIRR.COMP" (but seems to happen somewhat unpredictably). The other relevant args:

```
interval_len=60
interval_type="s"
ascend=True
timeout=5
```

An example of a request that caused the exception to get raised:

`HIT,USDIRR.COMP,60,20181119 000000,20190220180040,,000000,235959,1,H_0000000155,100,s,0
`

Any guidance would be greatly appreciated.

**Comment by stephenrs** [comment]
Hi, This is an ongoing issue. Any thoughts?

**Comment by akapur** [comment]
HI I can't replicate this. I don't know what is happening on your end. Could you please respond with exactly the code you are running AND the version of IQFeed.exe you are running.  Thanks.

**Comment by stephenrs** [comment]
Hi, Although I think there are a few conditions that can cause this, I was able to identify the scenario that I was running into most often, and fixed it by increasing the timeout (to 15 in my case).

I have a job that updates a historical database for a list of symbols by looping through the list and fetching trade/bar data that has become available since the last update. 

Also, rather than opening and closing a connection for each request (by using "with iq.connection..."), the job opens one history connection and reuses it for each symbol - closing the connection once all symbols have been processed.

However, sometimes a new symbol gets added to the list, so the entire back history needs to be fetched, which can take several seconds - and possible can also cause requests to overlap, given the way I've structured the update code, as described above.

So, by looking at conn.py, I was able to guesstimate that _cleanup_request_data() was getting called before all of the data had finished coming across the socket, when entire long histories were being fetched. So, by the time _process_datum() needs self._req_buf[req_id], it has already been deleted if the timeout hasn't been set high enough.

What made this particularly difficult was that once this exception is triggered, the HistoryConn becomes unusable, so any request_bars_in_period() calls that come after it will fail silently - and I couldn't find a way to handle the exception explicitly without modifying the pyiqfeed code.

Hopefully, this is enough to help you reproduce it, but let me know if you need more detail.

Also...a question: are HistoryConn objects meant to be long-lived/persistent the way that I'm treating them, or is your intention that they are only ever used to handle a single fetch request, then closed as suggested by the ConnConnector class? I ask because there are other scenarios where I'd like to reuse a HistoryConn connection, since shutting down sockets is naturally pretty slow.

Thanks!

**Comment by akapur** [comment]
Long lived like you are doing now.

I’ll figure out a way to recover from this kind of timeout error and provide better error handling. I do something similar myself but what I do is I make multiple requests one for each day of tick data rather than a single request for the entire history. This also makes things more efficient and uses memory much more efficiently.

Thanks.

Ashwin

**Comment by akapur** [comment]
Would you mind submitting a pull request for the changes to the pyiqfeed code. And or maybe send me what your changes are so I can incorporate them into the library.

Thanks.

**Comment by stephenrs** [comment]
Once I realized that I could work around the problem with a longer timeout, I didn't actually make any changes to the library. pyiqfeed is a solid library, and my skills with the python threading model aren't that solid, so I preferred not to risk potentially introducing instability. Sorry I can't be of more help, and thanks for taking a look at this.

Also, I'm only pulling 1 minute data, so I haven't run into any memory issues, and routine updates are very fast/efficient, but I can see how what you're doing would make more sense with tick data.
