### ISSUE TITLE
process_history_bar()

### ISSUE THREAD

**Issue by blonc** [akapur/pyiqfeed#46]
I'm not seeing a clear path to access `process_history_bar()` to actually process the returned array. could you please at the needed function to this piece of code from the example calling the function to process the history bar :

```
def get_live_interval_bars(ticker: str, bar_len: int, seconds: int):
    """Get real-time interval bars"""
    bar_conn = iq.BarConn(name='pyiqfeed-Example-interval-bars')
    bar_listener = iq.VerboseBarListener("Bar Listener")
    bar_conn.add_listener(bar_listener)

    with iq.ConnConnector([bar_conn]) as connector:
        bar_conn.watch(symbol=ticker, interval_len=bar_len,
                       interval_type='s', update=60, lookback_bars=5)
        bar_listener.process_history_bar(bar_conn.)
        time.sleep(seconds)
```

thank you

**Comment by akapur** [comment]
I don't understand your question.

**Comment by blonc** [comment]
cannot seem to override the `def process_history_bar(self, bar_data: np.array)` inside of `def get_live_interval_bars` to actually process the array vs just printing to command.  the above snippet works fine to simply output to command and I know that I need to override the function process_history_bar or process_live_bar to manipulate in real-time but can not seem to be able to do so.  Could you update the small snippet to show how you are overriding the process function?  Also, did you get access to IQ feed?

**Comment by blonc** [comment]
resolved  -thanks

**Comment by emilge** [comment]
@blonc Hey, could you share how you resolved this ? I have the same issue
