### ISSUE TITLE
Generic question on Wine crashes and how to limit downtime

### ISSUE THREAD

**Issue by karunkrishna** [akapur/pyiqfeed#51]
Currently running this on docker

-  If the autoheal detects that pyqfeed container is down it restarts. This usually takes about 15 minutes from last tick update
- As a result, I had implemented a heartbeat in my strategy itself to restart pyiqfeed-docker if update has not occurred for more than 3 heartbeats (3 minutes)
- Is there a recommended way of monitoring wine crashes, or pyiqfeed becoming unresponsive as restarting the docker-container is quite expensive in terms of downtime

**Comment by akapur** [comment]
I don’t run pyiqfeed inside a container. Don’t really have any advice to offer on the monitoring front, though I would love to hear what you find.

Frankly, in my usage, I don’t have many crashes. I do restart iqfeed.exe every 24 hours. I would want to look to see why crashes are happening. I literally don’t remember the last time I had a crash other than something that took a whole machine down or something like that.

**Comment by karunkrishna** [comment]
Sure, will investigate

I'll keep this ticket open for a few days to see if anyone else responds. 
I'll try restarting daily to see if that addresses the problem.
