### ISSUE TITLE
Generic Question: Canceling a specific realtime market data stream

### ISSUE THREAD

**Issue by karunkrishna** [akapur/pyiqfeed#52]
I have three strategies that all make requests for ES Futures but with varying bar_period 
- ES Futures at 60 seconds interval
- ES Futures at  200 tick interval
- ES Futures at 2 hour interval 
- 
There are times when my strategy disconnects( Say for example ES Futures at 60 seconds)
As a result I request the @ES#60sec again. 
This results in two active streams now for @ES#60sec 
Is there a way to cancel the previous listener (giving some kind of unique stream identifier string); and then making the required request again
I see a api for unwatching a symbol, but not sure if that would cancel all 3 of my marketdata as they are all @ES#

**Comment by akapur** [comment]
Unfortunately, there is no identifier for each request. So you are probably
going to have to unwatch and rewatch everything. Generally, when I want
bars at multiple intervals, I subscribe to bars at the smallest interval
size (or even all trades) and maintain bars at the larger interval sizes
myself.

I would try to figure out why IQFeed is dropping one of your requests. I
don't make requests for multiple bar sizes like you do but I haven't seen
IQFeed drop a real-time data request before. Unfortunately that is likely
an IQFeed issue not a pyiqfeed issue. pyiqfeed is only an interface on top
of IQFeed.

**Comment by karunkrishna** [comment]
Looking for some pointers on what has worked for you
I think I need to architecture how I am request market data per algo

- Are you running you iqfeed instance on windows or ubuntu-wine instance?
- What is your OS, CPU Core, RAM size like?
- For your architecture, are you using a pub/sub model? Redis etc?

**Comment by akapur** [comment]
Not an issue with pyiqfeed.
