### ISSUE TITLE
saving live data

### ISSUE THREAD

**Issue by fs4590** [akapur/pyiqfeed#57]
Hello, is there anyway you can add away to save the incoming live data for get_live_interval_bars please   ?
i did read the conn.py and i only were able to save it by using  elif bar_type == 'H': in the _process_bars(self, fields: Sequence[str]) function. but it does not save into a file right away . it will only save after i stope the connection
i am not experience developer , i just know basic python  .
been trying to do this since april 29 of this year .

**Comment by akapur** [comment]
pyiqfeed gets data. It doesn't save it. You will need to write code to save
it yourself.

**Comment by fs4590** [comment]
for those future readers who have similar issue .after akapur the creator if pyiqfeed explain to me that extra code needed to be added to save the data ,I was able to save streaming tick data by adding these lines after line 3210 in teh conn.py file, in teh elif bar_type =='c': statement ,right after the print(interval_data) add these lines.
 with open('live_data.csv','a+') as f:
     for line in interval_data:
         f.writelines("%s\n" % str(interval_data))

I hope this will help someone in teh future . 
akapur ,I thank you from teh bottoms of my heart 
![image](https://user-images.githubusercontent.com/34248169/200146811-61a598a9-aad2-48d0-bd57-3489375ef4dd.png)
